<MenuScreen>:
    BoxLayout:
        Button:
            text: "Generate Report"
            on_press: root.manager.current = 'report'
        Button:
            text: "View Data"
            on_press: root.manager.current = 'viewData'
        Button:
            text: "Filter Data"
            on_press: root.manager.current = 'filterData'
<ReportScreen>:
    BoxLayout:
        Button:
            text: "hello"